server.port=8082

spring.profiles.active=dev
spring.application.name=nextShop-product


# eureka
eureka.instance.instance-id=${spring.application.name}/${eureka.instance.ip-address}:${server.port}/${instanceId:${random.uuid}}

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone= ${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address= true
eureka.instance.ip-address= 127.0.0.1
eureka.instance.secure-port= ${server.port}