server.port=0

spring.profiles.active=dev
#spring.profiles.active=prod


# Eureka
spring.application.name=nextShop-product
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.uuid}}


# Minio
spring.minio.bucket.name=next-shop.product.image
spring.minio.access-key=nextShop
spring.minio.secret-key=nextShop
spring.minio.url=http://127.0.0.1:9008
