server.port=8082

spring.profiles.active=dev
#spring.profiles.active=prod


# Eureka
spring.application.name=nextShop-product
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.uuid}}

