spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: product-category
          uri: lb://product-service
          predicates:
            - Path=/api/v1/category/**
        - id: product-image
          uri: lb://product-service
          predicates:
            - Path=/api/v1/image/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: order-detail
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order-detail/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 8090