spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/nextShop-orders
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: validate
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}

  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      schema-registry-url: http://localhost:8081
      request-timeout-ms: 3000
      max-block-ms: 3000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.nextShop.order_service.dto.message_broker.OrderConfirmationDto

server:
  port: 8092

nextShop:
  config:
    product-service-url: http://localhost:8091/api/v1/product
    user-service-url: http://localhost:8093/api/v1/user
    payment-service-url: http://localhost:8094/api/v1/payment
