spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3309/nextShop-payment
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  #      ddl-auto: validate
  #  flyway:
  #    baseline-on-migrate: true
  #    enabled: true
  #    baseline-description: "init"
  #    baseline-version: 0
  #    user: ${spring.datasource.username}
  #    password: ${spring.datasource.password}

  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      schema-registry-url: http://localhost:8081
      request-timeout-ms: 3000
      max-block-ms: 3000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.nextShop.payment_service.dto.message_broker.PaymentNotificationRequestDto

server:
  port: 8094