spring.application.name=nextShop-auth
spring.profiles.active=dev
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:migrations/changelog-master.xml


eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}/${eureka.instance.ip-address}:\
    ${server.port}/${instanceId:${random.uuid}}

jwt.key=dzwe2X3IP9xE+M58cs88ccqrQqj8gpD9BicQWlVuOG7UOhq82/TK1fx56GEmdwislY6bfc3vqD8AAm6QcHvnUZ\
  eyOi+bKPbRLA1K1zp1qZamgsyg/Yu/XXkQduT8Qg1yJY4mrVMetikH+iSjjHdt7yGwHty2IArbFW0odacX1kJC0fn6DOU1Ns0yq3vBaVlp
