#server.port=0
server.port=8081

#Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:migrations/changelog-master.xml

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3310/nextShop-auth
spring.datasource.username=nextShop_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect