server.port=8761

spring.application.name=nextShop-discovery-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.ip-address=127.0.0.1

# warning
eureka.instance.lease-renewal-interval-in-seconds=0
eureka.server.enableSelfPreservation=true

